Sugamta.Web/Models/UserEntity.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.Data;

namespace Sugamta.Web.Models
{
	public class UserEntity
	{
		public int UserID { get; set; }

		public string Email { get; set; }
		public string Name { get; set; }
		//public string Image { get; set; }
	
		public string Password { get; set; }

       public int RoleId { get; set; }
        public string RoleType { get; set; }
        public DateTime CreationDate { get; set; }
		public string CreatedBy { get; set; }
		public int IsDeleted { get; set; } = 0;
        public string? OTP { get; set; }
		//public Role Roles { get; set; }
    }
}

Sugamta.Web/Controllers/UserEntityController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Sugamta.Web.Models;
using Sugamta.Web.Models.UserDTOs;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace Sugamta.Web.Controllers
{
    public class UserEntityController : Controller
    {
        // string apiUrl = "https://localhost:7109/api/User";
         string DeleteUrl = "https://localhost:7109/api/User";

        public UserEntityController()
        {
        }


        
        public async Task<ActionResult> Index()
        {
            List<UserEntity> userEntities = await GetUserEntitiesAsync();
            return View(userEntities);
        }

        //[Authorize(Roles = "Admin")]
        //[Authorize(Policy = "AdminPolicy")]
        [HttpGet]
        public async Task<ActionResult> UserEntityDetails()
        {
            return PartialView("_UserEntityDetails");
        }

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            List<UserEntity> userEntities = await GetUserEntitiesAsync();
            return Json(new { data = userEntities.ToList() });
        }

        public async Task<List<UserEntity>> GetUserEntitiesAsync()
        {
            List<UserEntity> userEntitiesWithRole = new List<UserEntity>();

            using (var client = new HttpClient())
            {
                string bearerToken = HttpContext.Session.GetString("BearerToken");

                // Set the Authorization header with the bearer token
                client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", bearerToken);

                HttpResponseMessage response = await client.GetAsync(ApiUrl);

                if (response.IsSuccessStatusCode)
                {
                    string content = await response.Content.ReadAsStringAsync();
                    List<UserEntity> userWithRoleDtos = JsonConvert.DeserializeObject<List<UserEntity>>(content);

                    userEntitiesWithRole = userWithRoleDtos.Select(dto =>
                        new UserEntity
                        {
                            Email = dto.Email,
                            Name = dto.Name,
                            Password = dto.Password,
                            CreationDate = dto.CreationDate,
                            IsDeleted = dto.IsDeleted,
                            RoleType = dto.RoleType
                        }).ToList();
                }
                else
                {
                    // Handle the error condition, you might want to log it or take other actions.
                    ModelState.AddModelError(string.Empty, "Failed to retrieve user entities. Please try again.");
                }

                return userEntitiesWithRole;
            }
        }

        [HttpGet]
        public async Task<ActionResult> Create()
        {
           //return View();
           return PartialView("_AddUserEntity");
        }

        string ApiUrl = "https://localhost:7109/api/User";
       
        string baseURL = "https://localhost:7109/api/User";
        [HttpPost]
        public async Task<IActionResult> Create(UserCreateDto user)
        {
            //UserEntity obj = new UserEntity()
            //{
            //    // UserID = user.UserID,
            //    Email = user.Email,
            //    Name = user.Name,
            //    Password = user.Password,
            //    RoleId = user.RoleId,
            //    CreationDate = DateTime.Now,
            //   CreatedBy = user.Email,
            //    IsDeleted = user.IsDeleted,
            //    //UpdationDate = user.UpdationDate,
            //};
            if (user.Email != null)
            {

                using (var client = new HttpClient())
                {
                    HttpResponseMessage getData = await client.PostAsJsonAsync<UserCreateDto>("https://localhost:7109/api/User/create-user", user);

                    if (getData.IsSuccessStatusCode)
                    {
                        return RedirectToAction("UserEntityDetails");

                    }
                    else
                    {
                        Console.WriteLine("Error Calling Web API");
                    }

                }
            }
            return View();
        }

        [HttpGet]
        public async Task<ActionResult> Edit(string email)
        {
            UserDetails userDetails = new()
            {
                Email = email
            };

            using (var client = new HttpClient())
            {

                string apiUrl = $"https://localhost:7109/api/get-user-details/{Uri.EscapeDataString(userDetails.Email)}";

                HttpResponseMessage response = await client.GetAsync(apiUrl);

                if (response.IsSuccessStatusCode)
                {
                    string content = await response.Content.ReadAsStringAsync();
                    UserDetails fetchedUserDetails = JsonConvert.DeserializeObject<UserDetails>(content);
                    return PartialView("_EditUserEntity", fetchedUserDetails);
                }
            }

            return PartialView("_EditUserEntity");
        }

         public async Task<UserEntity> GetUserEntityByEmailAsync(string email)   
         {
              using (var client = new HttpClient())
              {
                string apiUrl1 = $"https://localhost:7109/api/User/{Uri.EscapeDataString(email)}";
                HttpResponseMessage response = await client.GetAsync(apiUrl1);

                  if (response.IsSuccessStatusCode)
                  {
                      string content = await response.Content.ReadAsStringAsync();
                      UserEntity userEntity = JsonConvert.DeserializeObject<UserEntity>(content);
                      return userEntity;
                  }
                  else
                  {
                      return null; 
                  }
              }
         }

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> Edit(string email, UserEntity userEntity)
        //{
        //    try
        //    {
        //        if (email != userEntity.Email)
        //        {
        //            return NotFound();
        //        }

        //        using (var client = new HttpClient())
        //        {
        //            string editApiUrl = $"https://localhost:7109/api/User/update-user/{Uri.EscapeDataString(email)}";
        //            string serializedUserEntity = JsonConvert.SerializeObject(userEntity);
        //            var content = new StringContent(serializedUserEntity, Encoding.UTF8, "application/json");

        //            HttpResponseMessage response = await client.PutAsync(editApiUrl, content);

        //            if (response.IsSuccessStatusCode)
        //            {
        //                //  return RedirectToAction("Index");
        //                //return RedirectToAction("_UserEntityDetails");
        //                return View("_UserEntityDetails", "userEntities");
        //               // return PartialView("_UserEntityDetails", "userEntities");
        //            }
        //            else
        //            {
        //                var errorMessage = await response.Content.ReadAsStringAsync();
        //                Console.WriteLine($"Error: {response.StatusCode} - {errorMessage}");


        //                ModelState.AddModelError(string.Empty, "Failed to update user. Please try again.");

        //                return View(userEntity);
        //            }
        //        }
        //    }
        //    catch (Exception ex)
        //    {
        //        Console.WriteLine($"Exception: {ex.Message}");


        //        ModelState.AddModelError(string.Empty, "An unexpected error occurred. Please try again.");

        //        return View(userEntity);
        //    }
        //}

        //[HttpPost]
        //public async Task<ActionResult> Edit(UserUpdateDto userEntity)
        //{
        //    try
        //    {
        //        var formData = new MultipartFormDataContent();

        //        formData.Add(new StringContent(userEntity.Email), "Email");
        //        formData.Add(new StringContent(userEntity.Name), "Name");
        //        formData.Add(new StringContent(userEntity.Password), "Password");
        //        //formData.Add(new StringContent(userEntity.RoleId.ToString()), "RoleId");

        //        using (var client = new HttpClient())
        //        {
        //            HttpResponseMessage response = await client.PutAsync("https://localhost:7109/api/User/update-user-without-otp", formData);

        //            if (response.IsSuccessStatusCode)
        //            {
        //                //  return RedirectToAction("Index");
        //                //return RedirectToAction("_UserEntityDetails");
        //                return View("_UserEntityDetails", "userEntities");
        //                // return PartialView("_UserEntityDetails", "userEntities");
        //            }
        //            else
        //            {
        //                var errorMessage = await response.Content.ReadAsStringAsync();
        //                Console.WriteLine($"Error: {response.StatusCode} - {errorMessage}");


        //                ModelState.AddModelError(string.Empty, "Failed to update user. Please try again.");

        //                return View(userEntity);
        //            }
        //        }
        //    }
        //    catch (Exception ex)
        //    {
        //        Console.WriteLine($"Exception: {ex.Message}");


        //        ModelState.AddModelError(string.Empty, "An unexpected error occurred. Please try again.");

        //        return View(userEntity);

Sugamta.Web/Views/UserEntity/Create.cshtml
 @model Sugamta.Web.Models.UserEntity

@{
    ViewData["Title"] = "Create";
}
@* <style>
    form input{
        width:;
    }
</style> *@

<form id="createUserForm" asp-action="Create" asp-controller="UserEntity" method="post">
   @*  <div class="form-group">
        <label for="floatingInput">UserID:</label>
        <input id="userIdInput" asp-for="UserID" type="email" class="form-control" id="floatingInput" placeholder="" />

    </div> *@
    <div class="form-group">
        <label for="floatingInput">Email:</label>
        <input id="emailInput1" asp-for="Email" type="email" class="form-control" id="floatingInput" placeholder="examp@gmail.com"style="width:355px;margin-left:111px;margin-top:-37px" />

    </div>
    <div class="form-group">
        <label for="floatingInput">Name:</label>
        <input id="nameInput" asp-for="Name" type="text" class="form-control" placeholder="name" style="width:355px;margin-left:111px;margin-top:-37px" />
    </div>
    <div class="form-group">
        <label for="floatingInput">Password:</label>
        <input id="passwordInput" asp-for="Password" type="password" class="form-control" placeholder="" style="width:355px;margin-left:111px;margin-top:-37px" />

    </div>
    <div class="form-group">
        <label for="floatingInput">RoleType:</label>
        <select asp-for="RoleType" type="text" class="form-control form-select form-select-sm " id="floatingInput" aria-label="small select example" style="width:355px;margin-left:111px;margin-top:-37px">

            <option selected></option>
            <option value="1">Admin</option>
            <option value="2">Agent</option>
            <option value="3">Investor</option>
            <option value="4">Client</option>
            <option value="4">Agency</option>
        </select>
       @*  <input id="roleIdInput" asp-for="RoleId" type="number" class="form-control" placeholder="012.." style="width:355px;margin-left:111px;margin-top:-37px" /> *@

    </div>
    <div class="form-group">
        <label for="floatingInput">CreationDate:</label>
        <input id="creationDateInput" asp-for="CreationDate" type="date" class="form-control" placeholder="mm/dd/yyyy" style="width:355px;margin-left:111px;margin-top:-37px" />

    </div>
    
    <div class="form-group">
        <label for="floatingInput">IsDeleted:</label>
        <input id="isDeletedInput" asp-for="IsDeleted" type="number" class="form-control" placeholder="012.." style="width:355px;margin-left:111px;margin-top:-37px" />

    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-primary" onclick="submitCreateUserForm()" >Save</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="closeCreateModal()" style="margin-right:299px">Cancel</button>
       
    </div>
</form>

<script>
  
  
    function submitCreateUserForm() {
        $.ajax({
            url: '/UserEntity/Create',
            type: 'POST',
            data: $('#createUserForm').serialize(),
            success: function (data) {
                $('#UserDetailsTable').html(data);
                
            },
            error: function () {
               
            }
                
        });

        
        closeCreateModal();
    }

</script>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Sugamta.Web/Views/UserEntity/Delete.cshtml
@model Sugamta.Web.Models.UserEntity

@{
    ViewData["Title"] = "Delete User";
}

<h1>Delete</h1>

    <div id="deleteModalContainer">
        @await Html.PartialAsync("_DeleteUserModal",Model)
    </div>

Sugamta.Web/Views/UserEntity/Edit.cshtml
 @model Sugamta.Web.Models.UserEntity

@{
    ViewData["Title"] = "Edit";
}

<hr />
<div class="row">
    <div class="col-md-4">
        <div id="editUserModalContainer">
            @await Html.PartialAsync("_EditUserEntity")
        </div>
    </div>
</div>
@* @section Scripts
{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
} 
 *@

Sugamta.Web/Views/UserEntity/UserEntityDetails.cshtml
 @model List<Sugamta.Web.Models.UserEntity>

@{
    ViewData["Title"] = "User Details";
}



<h2>User Details</h2>

@* <div id="UserDetailsContainer">
    @Html.Partial("_UserEntityDetails")
</div>  *@

<h2>User Details</h2>

@if (Model != null && Model.Any())
{
    <div id="UserDetailsContainer">
        @Html.Partial("_UserEntityDetails")
    </div>
}
else
{
    <p>No user details available.</p>
}

Sugamta.Web/Views/UserEntity/_AddUserEntity.cshtml
@model UserEntity

@* <div id="profilePopup" class="modal fade profileform">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content pl-4 pr-4"> *@
            <!-- Popup content goes here -->
            <form asp-controller="Home" asp-action="AddOrUpdateUserDetails" method="post" enctype="multipart/form-data">
                <div class="modal-header" style="padding: 16px 0 !important;">
                    <h5 class="modal-title">Create User</h5>
                    <button type="button" class="close" style="color: red;" data-dismiss="modal" onclick="closeModal1()">&times;</button>
                </div>
                <div class="row">
                    <div class="modal-body col-12">
                        <!-- Your profile content goes here -->
                        <div class="form-floating mb-2">
                            <label for="floatingInput">Email</label>
                            <input id="emailInput" asp-for="Email" type="email" class="form-control input-sm" id="floatingInput" placeholder="examp@gmail.com">
                        </div>

                        <div class="form-floating mb-2">
                            <label for="floatingInput">Name</label>
                            <input id="addressInput" asp-for="Name" type="text" class="form-control input-sm" id="floatingInput" placeholder="name">
                        </div>

                        <div class="form-floating mb-2">
                            <label for="floatingInput">Password</label>
                            <input id="cityInput" asp-for="Password" type="text" class="form-control input-sm" id="floatingInput" placeholder="name">
                        </div>

                        <div class="form-floating mb-2">
                            <label for="floatingInput">Role Type</label>
                <select id="roleInput" asp-for="RoleId" class="form-control form-select form-select-sm" aria-label="small select example" style="width: 65%; margin-left: 151px; z-index: 1000;">
                                <option selected>--Select Role--</option>
                                <option value="1">Admin</option>
                                <option value="2">Agent</option>
                                <option value="3">Investor</option>
                                <option value="4">Client</option>
                                <option value="5">Agency</option>
                            </select>
                        </div>

                        <button type="submit" class="btn btn-lg btn-primary btn-login text-uppercase mb-2" style="padding: 6px 18px 5px 18px;
                        margin-top: 8px;
                        font-size: 15px;
                        font-family: sans-serif;
                        font-weight: lighter;">
                            Save
                        </button>
                        <button class="btn btn-lg btn-outline-dark text-uppercase mb-2" type="button" style="padding: 6px 18px 5px 18px;
                        margin-top: 8px;
                        font-size: 15px;
                        font-family: sans-serif;
                        font-weight: lighter;" onclick="closeModal1()">
                            Cancel
                        </button>
                    </div>

                </div>
            </form>
@*         </div>
    </div>
</div> *@

Sugamta.Web/Views/UserEntity/_DeleteUserModal.cshtml
<style>
    .btn-secondary:hover {
        color: red;
    }

   
</style>


<div id="deleteUserModal" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered custom-modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Delete User</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="closeDeleteModal()">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body custom-modal-body">
                <p>Are you sure you want to delete this user?</p>
                <form id="deleteUserForm" asp-action="Delete" asp-controller="UserEntity" method="post">
                    <input type="hidden" id="deleteEmail" name="email" />
                    
                </form>
            </div>
            <!---->
            <div class="modal-footer">
               @*  <button type="button" class="btn btn-danger" onclick="submitDeleteUserForm()">Delete</button> *@
                <button type="submit" class="btn btn-lg btn-danger btn-login text-uppercase mb-2" onclick="submitDeleteUserForm()" style="padding: 6px 18px 5px 18px;
                       
                        font-size: 15px;
                        font-family: sans-serif;
                        font-weight: lighter;" >
                    Delete
                </button>
                @* <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="closeDeleteModal()" style="margin-right:318px">Cancel</button> *@
                <button class="btn btn-lg btn-outline-dark text-uppercase mb-2" data-dismiss="modal" type="button" onclick="closeDeleteModal()" style="padding: 6px 18px 5px 18px;
                        margin-right:267px;
                        font-size: 15px;
                        font-family: sans-serif;
                        font-weight: lighter;">
                    Cancel
                </button>
              
            </div>
        </div>
    </div>
</div>


<script>


    function deleteUserData(email) {
        $('#deleteEmail').val(email);
        $('#deleteUserModal').modal('show');
    }
 
    function submitDeleteUserForm() {
        $.ajax({
            url: '/UserEntity/Delete',
            type: 'POST',
            data: $('#deleteUserForm').serialize(),
            success: function (data) {
                debugger;
                console.log('User deleted successfully');
                $('#deleteUserModal').modal('hide');
                
            },
            error: function (error) {
                console.error('Error deleting user:', error);
            }
        });
        location.reload();
    }
 
    function closeDeleteModal() {
        $('#deleteUserModal').modal('hide');
    }


    

</script>

Sugamta.Web/Views/UserEntity/_EditUserEntity.cshtml
@model UserDetails

@* <div id="profilePopup" class="modal fade profileform">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content pl-4 pr-4"> *@
<!-- Popup content goes here -->
<form asp-controller="Home" asp-action="AddOrUpdateUserDetails" method="post" enctype="multipart/form-data">
    <div class="modal-header" style="padding: 16px 0 !important;">
        <h5 class="modal-title">User Profile</h5>
        <button type="button" class="close" style="color: red;" data-dismiss="modal" onclick="closeModal1()">&times;</button>
    </div>
    <div class="row">
        <div class="modal-body col-9">
            <!-- Your profile content goes here -->
            <div class="form-floating mb-2">
                <label hidden for="floatingInput">Email</label>
                <input id="emailInput" asp-for="Email" hidden type="email" class="form-control input-sm" id="floatingInput" placeholder="examp@gmail.com" disabled>

            </div>

            <div class="form-floating mb-2">
                <label for="floatingInput">Address</label>
                <input id="addressInput" asp-for="Address" type="text" class="form-control input-sm" id="floatingInput" placeholder="name">
            </div>
            <div class="form-floating mb-2">
                <label for="floatingInput">City</label>
                <input id="cityInput" asp-for="City" type="text" class="form-control input-sm" id="floatingInput" placeholder="name">
            </div>

            <div class="form-floating mb-3">
                <label for="stateInput">State</label>
                <select id="stateInput" asp-for="StateId" class="form-control form-select form-select-sm" aria-label="small select example" style="width: 359px; margin-left: 151px;">
                    <option selected></option>
                    @foreach (var state in ViewBag.StateList as List<State> ?? new List<State>())
                    {
                        <option value="@state.StateId">@state.StateName</option>
                    }
                </select>
            </div>
            <div class="form-floating mb-3">
                <label for="countryInput">Country</label>
                <select id="countryInput" asp-for="CountryId" class="form-control form-select form-select-sm" aria-label="small select example" style="width: 359px; margin-left: 151px; z-index: 1000;">
                    <option selected></option>
                    @foreach (var country in ViewBag.CountryList as List<Country> ?? new List<Country>())
                    {
                        <option value="@country.CountryId">@country.CountryName</option>
                    }
                </select>
            </div>


            <div class="form-floating mb-2">
                <label for="floatingInput">Phone Number</label>
                <input id="phoneInput" asp-for="PhoneNumber" type="number" class="form-control input-sm" id="floatingInput" placeholder="12345">

            </div>
            <div class="form-floating mb-2">
                <label for="floatingInput">Alternate PhoneNo</label>
                <input id="alternatePhoneInput" asp-for="AlternatePhoneNumber" type="number" class="form-control input-sm" id="floatingInput" placeholder="123..">

            </div>

            <div class="form-floating mb-2">
                <label>Profile Picture:</label>
                <div class="input-group" style="width: 92%;">
                    <input type="file" id="formFile" class="form-control" asp-for="formFile" onchange="previewImage(this)">
                </div>
            </div>

            <button type="submit" class="btn btn-lg btn-primary btn-login text-uppercase mb-2" style="padding: 6px 18px 5px 18px;
                        margin-top: 8px;
                        font-size: 15px;
                        font-family: sans-serif;
                        font-weight: lighter;">
                Save
            </button>
            <button class="btn btn-lg btn-outline-dark text-uppercase mb-2" type="button" style="padding: 6px 18px 5px 18px;
                        margin-top: 8px;
                        font-size: 15px;
                        font-family: sans-serif;
                        font-weight: lighter;" onclick="closeModal1()">
                Cancel
            </button>
        </div>

        <div class="col-3" style="position: relative;">
            <img asp-formaction="" class="userImage" id="imagePreview" width="100%" style="margin-top: 20px; height: 160px; border: solid;" />

            @if (Model != null && Model.ImageUrl != null)
            {
                <input type="hidden" id="previousImageUrl" src="@Model.ImageUrl" />
            }

            <button type="button" class="btn btn-custom"
                    onclick="discardImage()">
                <i class="fas fa-trash-alt" style="color:brown;"></i>
            </button>
        </div>


    </div>
</form>
@*         </div>
    </div>
</div> *@

Sugamta.Web/Views/UserEntity/_UserEntityDetails.cshtml
@model List<UserEntity>

<div class="card shadow border-0 my-4">
    @* <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">User List</h2>
            </div>
        </div>
    </div> *@
    <div class="card-body p-4">
        <div class="row pb-3">
            <div class="col-6">
            </div>
@*             <div class="col-6 text-end">
                <a asp-controller="Product" asp-action="Upsert" class="btn btn-primary">
                    <i class="bi bi-plus-circle"></i> Add New User
                </a>
            </div> *@
        </div>

        <table id="tblData" class="table table-bordered " style="width:100%">
            <thead>
                <tr>
                    <th>Email</th>
                    <th>Name</th>
                    <th>Creation Date</th>
                    <th>Role</th>
                    <th >
                        <div style="display: flex; justify-content: center;">
                            <button type="button" style="background: #33cfa4 !important; border: none;" onclick="RenderUserAddView();" class="btn btn-primary">
                                <i class="bi bi-plus-circle"></i> Add New User
                            </button>
                        </div>
                    </th>
                </tr>
            </thead>
        </table>

    </div>
</div>

@section Scripts {
    <script src="~/js/UserEntityDetails.js"></script>
}

<script src="~/js/AddUserView.js"></script>