Sugamta.Web/Models/SecondaryClient.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;
using System.Text.Json.Serialization;

namespace Sugamta.Web.Models
{
    public class SecondaryClient
    {


        public string SecondaryClientEmail { get; set; }

        public string Name { get; set; }

        public string Password { get; set; }

        public DateTime? CreationDate { get; set; }
        public int? RoleId { get; set; }
        [ForeignKey("RoleId")]
        [JsonIgnore]
        [ValidateNever]
       
        public string? OTP { get; set; }
        public int? IsDeleted { get; set; } = 0;

        // public int IsDeleted { get; set; } = 0;
        [ForeignKey("PrimaryClient")]
        public string PrimaryClientEmail { get; set; }
        public string RoleType { get; set; }

    }
}

Sugamta.Web/Models/SecondaryClientDetails.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sugamta.Web.Models
{
    public class SecondaryClientDetails
    {
        public List<State> States { get; set; }
        public List<Country> Countries { get; set; }
        public string SecondaryClientEmail { get; set; }
        public IFormFile? formFile { get; set; }
      //  public string Name { get; set; }

        public string Address { get; set; }
       // public string Gender { get; set; }
        //public int Age { get; set; }
        public string City { get; set; }
        public int StateId { get; set; }
        public int CountryId { get; set; }
        public string PhoneNumber { get; set; }
        public string AlternatePhoneNumber { get; set; }
        public string CreationDate { get; set; }
        public DateTime UpdationDate { get; set; }
        public byte[]? ImageUrl { get; set; }
       
    }
}

Sugamta.Web/Controllers/SecondaryClientController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Sugamta.Web.Models;
using Sugamta.Web.Models.SecondaryClientDTOs;
using Sugamta.Web.Models.UserDTOs;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text;
using System.Threading.Tasks;

namespace Sugamta.Web.Controllers
{
    public class SecondaryClientController : Controller
    {
        private readonly string ApiUrl = "https://localhost:7109/api/get-all-secondary-client";
        private readonly string AddSecondaryClientApiUrl = "https://localhost:7109/api/add-secondary-client-records";

        public SecondaryClientController()
        {
        }

        [HttpGet]
        public async Task<ActionResult> Index()
        {
            List<SecondaryClient> userEntities = await GetUserEntitiesAsync();
            return View(userEntities);
        }

        [HttpGet]
        public async Task<ActionResult> GetSecondaryClient()
        {
            return PartialView("_SecondaryClientDetail");
        }

        [HttpGet]
        public async Task<IActionResult> GetAll1()
        {
            List<SecondaryClient> userEntities = await GetUserEntitiesAsync();
            return Json(new { data = userEntities.ToList() });
        }

        [HttpGet]
        public async Task<ActionResult> Create()
        {
            return PartialView("_AddSecondaryClient");
        }

        [HttpPost]
        public async Task<IActionResult> Create(SecondaryClientCreateDto user)
        {
            if (user.SecondaryClientEmail != null)
            {
                using (var client = new HttpClient())
                {
                    try
                    {
                        HttpResponseMessage getData = await client.PostAsJsonAsync<SecondaryClientCreateDto>("https://localhost:7109/api/add-secondary-client-records", user);

                        if (getData.IsSuccessStatusCode)
                        {
                            TempData["SecondaryClientRegistration"] = "Secondary Client Registered Successfully";
                            return RedirectToAction("HomePage", "Home");
                            // return RedirectToAction("GetSecondaryClient");
                        }
                        else
                        {
                            Console.WriteLine("Error Calling Web API");
                        }
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine($"Exception: {ex.Message}");
                    }
                }
            }

            return View();
        }

        private async Task<List<SecondaryClient>> GetUserEntitiesAsync()
        {
            List<SecondaryClient> userEntitiesWithRole = new List<SecondaryClient>();

            using (var client = new HttpClient())
            {
                string bearerToken = HttpContext.Session.GetString("BearerToken");

                // Set the Authorization header with the bearer token
                client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", bearerToken);

                try
                {
                    HttpResponseMessage response = await client.GetAsync(ApiUrl);

                    if (response.IsSuccessStatusCode)
                    {
                        string content = await response.Content.ReadAsStringAsync();
                        List<SecondaryClient> userWithRoleDtos = JsonConvert.DeserializeObject<List<SecondaryClient>>(content);

                        userEntitiesWithRole = userWithRoleDtos.Select(dto =>
                            new SecondaryClient
                            {
                                SecondaryClientEmail = dto.SecondaryClientEmail,
                                Name = dto.Name,
                                Password = dto.Password,
                                CreationDate = dto.CreationDate,
                                RoleType = dto.RoleType
                            }).ToList();
                    }
                    else
                    {
                        // Handle the error condition, you might want to log it or take other actions.
                        ModelState.AddModelError(string.Empty, "Failed to retrieve user entities. Please try again.");
                    }
                }
                catch (Exception ex)
                {
                    // Handle exception appropriately
                    Console.WriteLine($"Exception: {ex.Message}");
                }

                return userEntitiesWithRole;
            }
        }


        public async Task<IActionResult> GetProfileImageSecondaryClient(string email)
        {

            using (var client = new HttpClient())
            {
                string secClientImageURL = $"https://localhost:7109/api/secondary-client/secondory-client-image/{Uri.EscapeDataString(email)}";

                HttpResponseMessage response = await client.GetAsync(secClientImageURL);

                if (response.IsSuccessStatusCode)
                {
                    // Assuming the API returns a base64 string directly
                    string base64Image = await response.Content.ReadAsStringAsync();

                    // Return the base64 string as content with appropriate content type
                    return Content(base64Image, "image/png"); // Adjust content type based on your image format
                }
                else
                {
                    // Return a not found result or handle the error based on your application logic
                    return NotFound();
                }
            }
        }


        [HttpGet]
        public async Task<ActionResult> Edit(string email)
        {
            ViewData["SecondaryClientEmail"] = email;
            SecondaryClientDetails userDetails = new()
            {
                SecondaryClientEmail = email
            };

            using (var client = new HttpClient())
            {

                string apiUrl = $"https://localhost:7109/api/secondary-client/get-secondary-client-details/{Uri.EscapeDataString(email)}";

                HttpResponseMessage response = await client.GetAsync(apiUrl);

                if (response.IsSuccessStatusCode)
                {
                    string content = await response.Content.ReadAsStringAsync();
                    SecondaryClientDetailsEditDtos fetchedUserDetails = JsonConvert.DeserializeObject<SecondaryClientDetailsEditDtos>(content);
                    return PartialView("_EditSecondaryClient", fetchedUserDetails);
                }
            }

            return PartialView("_EditSecondaryClient");
        }

        public async Task<SecondaryClientDetails> GetUserEntityByEmailAsync(string email)
        {
            using (var client = new HttpClient())
            {
                string apiUrl1 = $"https://localhost:7109/api/get-all-secondary-client/{Uri.EscapeDataString(email)}";
                HttpResponseMessage response = await client.GetAsync(apiUrl1);

                if (response.IsSuccessStatusCode)
                {
                    string content = await response.Content.ReadAsStringAsync();
                    SecondaryClientDetails userEntity = JsonConvert.DeserializeObject<SecondaryClientDetails>(content);
                    return userEntity;
                }
                else
                {
                    return null;
                }
            }
        }

        public async Task<SecondaryClientDetails> GetSecondaryClientDetailsForCreationOrUpdate(string email)
        {
            using (var client = new HttpClient())
            {
                string getSecondaryClientURL = $"https://localhost:7109/api/secondary-client/get-secondary-client-details/{Uri.EscapeDataString(email)}";

                HttpResponseMessage response = await client.GetAsync(getSecondaryClientURL);

                if (response.IsSuccessStatusCode)
                {
                    // Assuming the API returns JSON
                    // UserDetails userDetails = await response.Content.ReadAsAsync<UserDetails>();
                    // return userDetails;
                    string content = await response.Content.ReadAsStringAsync();

                    // Deserialize the string into UserDetailsDto using JSON serializer
                    SecondaryClientDetails userDetails = JsonConvert.DeserializeObject<SecondaryClientDetails>(content);

                    return userDetails;
                }
                else
                {
                    return null;
                }
            }
        }

        string UpdateSecondaryClientDetailsURL = "https://localhost:7109/api/secondary-client/update-secondary-client-details";
        string AddSecondaryClientDetailsURL = "https://localhost:7109/api/secondary-client/add-secondary-client-details";
        [HttpPost]
        public async Task<IActionResult> AddOrUpdateSecondaryClientDetails(SecondaryClientDetailsCreateOrUpdateDtos userDetails)
        {
            try
            {
                // userDetails.SecondaryClientEmail = HttpContext.Session.GetString("SecondaryClientEmail");

                var existingUser = await GetSecondaryClientDetailsForCreationOrUpdate(userDetails.SecondaryClientEmail);

                var formData = new MultipartFormDataContent();

                formData.Add(new StringContent(userDetails.SecondaryClientEmail), "SecondaryClientEmail");
                // formData.Add(new StringContent(userDetails.Name), "Name");
                formData.Add(new StringContent(userDetails.Address), "Address");
                formData.Add(new StringContent(userDetails.City), "City");
                /* formData.Add(new StringContent(userDetails.StateId), "State");

Sugamta.Web/Views/SecondaryClient/_AddSecondaryClient.cshtml
@model SecondaryClient

@* <div id="profilePopup" class="modal fade profileform">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content pl-4 pr-4"> *@
<!-- Popup content goes here -->
<form asp-controller="SecondaryClient" asp-action="Create" method="post">
    <div class="modal-header">
        <h5 class="modal-title" style="margin-left: -16px">Secondary Client</h5>
        <button type="button" class="close" style="color: red;" data-dismiss="modal" onclick="closeAddModalSecondaryClient()">&times;</button>
    </div>
      <div class="row">
        <div class="modal-body col-9">
            <!-- Your profile content goes here -->
            <div class="form-floating mb-3">
                <label for="secondaryemailInput">Email</label>
                <input id="secondaryemailInput" asp-for="SecondaryClientEmail" type="email" class="form-control input-sm" placeholder="Enter secondary client email">
            </div>

            <div class="form-floating mb-3">
                <label for="nameInput">Name</label>
                <input id="nameInput" asp-for="Name" type="text" class="form-control input-sm" placeholder="Enter name">
            </div>
   
            <div class="form-floating mb-3">
                <label for="passwordInput">Password</label>
                <input id="passwordInput" asp-for="Password" type="password" class="form-control input-sm" placeholder="Enter password">
            </div>

            <div class="form-floating mb-3">
                <label for="roleIdInput">Role Type</label>
                <select asp-for="RoleId" class="form-control input-sm" required style="width: 359px;
                   margin-left: 150px">
                    <option value="7">Secondary Client</option>
                </select>
            </div>

            <div class="form-floating mb-3">
                <label for="primaryemailInput">Primary Client Email</label>
                <input id="primaryemailInput" asp-for="PrimaryClientEmail" type="email" class="form-control input-sm" placeholder="Enter primary client email">
            </div>

            
            <button type="submit" class="btn btn-lg btn-primary btn-login text-uppercase mb-2" style="padding: 6px 18px 5px 18px;
                        margin-top: 8px;
                        font-size: 15px;
                        font-family: sans-serif;
                        font-weight: lighter;">
                Save
            </button>
            <button class="btn btn-lg btn-outline-dark text-uppercase mb-2" type="button" style="padding: 6px 18px 5px 18px;
                        margin-top: 8px;
                        font-size: 15px;
                        font-family: sans-serif;
                        font-weight: lighter;" onclick="closeAddModalSecondaryClient()">
                Cancel
            </button>
        </div>

    </div>
</form>

<script>

    function closeAddModalSecondaryClient() {
        // Assuming you're using jQuery for Bootstrap modal
        $('#secondaryclientAddModal').modal('hide');
    }
</script>

Sugamta.Web/Views/SecondaryClient/_EditSecondaryClient.cshtml
@model Sugamta.Web.Models.SecondaryClientDTOs.SecondaryClientDetailsEditDtos
@{
    var SecondaryClientEmail = ViewData["SecondaryClientEmail"];
}


<form asp-controller="SecondaryClient" asp-action="AddOrUpdateSecondaryClientDetails" method="post" enctype="multipart/form-data">
    <div class="modal-header">
        <h5 class="modal-title"style="margin-left:-16px;">Secondary Client Details</h5>
        <button type="button" class="close" style="color: red;" data-dismiss="modal" onclick="closeModalSecondaryClient()">&times;</button>
    </div>
    <div class="row">
        <div class="modal-body col-9">
            <!-- Your profile content goes here -->
            @* <div class="form-floating mb-2">
                <label hidden for="floatingInput">Email</label>
                <input id="emailInput" asp-for="SecondaryClientEmail" hidden type="email" class="form-control input-sm" id="floatingInput" placeholder="examp@gmail.com" disabled>

            </div> *@

            <div class="form-floating mb-2">
                <label for="floatingInput">Email</label>

                @if (Model == null)
                {
                    <!-- Display the email value, but disable the input -->
                    <input id="emailInput" asp-for="SecondaryClientEmail" disabled value="@SecondaryClientEmail" type="email" class="form-control input-sm" id="floatingInput" mailto:placeholder="examp@gmail.com">

                    <!-- Hidden input to store the email value for submission -->
                    <input type="hidden" asp-for="SecondaryClientEmail" value="@SecondaryClientEmail" />
                }
                else
                {
                    <!-- Display the email value as a disabled input -->
                    <input id="emailInput" asp-for="SecondaryClientEmail" disabled type="email" class="form-control input-sm" id="floatingInput" mailto:placeholder="examp@gmail.com">

                    <!-- Hidden input to store the email value for submission -->
                    <input type="hidden" asp-for="SecondaryClientEmail" />
                }
            </div>

            <div class="form-floating mb-2">
                <label for="floatingInput">Address</label>
                <input id="addressInput" asp-for="Address" type="text" class="form-control input-sm" id="floatingInput" placeholder="name">
            </div>
            <div class="form-floating mb-2">
                <label for="floatingInput">City</label>
                <input id="cityInput" asp-for="City" type="text" class="form-control input-sm" id="floatingInput" placeholder="name">
            </div>
@* 
            <div class="form-floating mb-3">
                <label for="stateInputSecondaryClient">State</label>
                <div style="display:flex">
                 <select id="stateInputSecondaryClient" asp-for="StateId" class="form-control form-select form-select-sm" aria-label="small select example" style="width: 359px; margin-left: 151px;">
                    <option selected></option>
                    @foreach (var state in ViewBag.StateList as List<State> ?? new List<State>())
                    {
                        <option value="@state.StateId">@state.StateName</option>
                    }
                </select> 
                </div>
            </div>
            <div class="form-floating mb-3">
                <label for="countryInputSecondaryClient">Country</label>
                <div style="display:flex">
                <select id="countryInputSecondaryClient" asp-for="CountryId" class="form-control form-select form-select-sm" aria-label="small select example" style="width: 359px; margin-left: 151px; z-index: 1000;">
                    <option selected></option>
                    @foreach (var country in ViewBag.CountryList as List<Country> ?? new List<Country>())
                    {
                        <option value="@country.CountryId">@country.CountryName</option>
                    }
                </select>
                </div>
            </div> *@
             <div class="form-floating mb-3">
     <label for="stateInputSecondaryClient">State</label>
     <div style="display: flex;">
         <input id="" style="width: 32%;" asp-for="State" type="text" class="form-control input-sm" id="floatingInput" placeholder="state">
         <select id="stateInputSecondaryClient" asp-for="StateId" class="form-control form-select form-select-sm" aria-label="small select example" style="width: 33%;">
            @*  @ <option selected></option> @ *@
             @foreach (var state in ViewBag.StateList as List<State> ?? new List<State>())
             {
                 <option value="@state.StateId">@state.StateName</option>
             }
         </select>
     </div>

 </div>
 <div class="form-floating mb-3">
     <label for="countryInputSecondaryClient">Country</label>
     <div style="display: flex;">
         <input id="" style="width: 32%;" asp-for="Country" type="text" class="form-control input-sm" id="floatingInput" placeholder="country">
         <select id="countryInputSecondaryClient" asp-for="CountryId" class="form-control form-select form-select-sm" aria-label="small select example" style="width: 33%; z-index: 1000;">
             @* @ <option>--Select Country--</option> @ *@
             @foreach (var country in ViewBag.CountryList as List<Country> ?? new List<Country>())
             {
                 <option selected value="@country.CountryId">@country.CountryName</option>
             }
         </select>
     </div>              
 </div>

            <div class="form-floating mb-2">
                <label for="floatingInput">Phone Number</label>
                <input id="phoneInput" asp-for="PhoneNumber" type="number" class="form-control input-sm" id="floatingInput" placeholder="12345">

            </div>
            <div class="form-floating mb-2">
                <label for="floatingInput">Alternate PhoneNo</label>
                <input id="alternatePhoneInput" asp-for="AlternatePhoneNumber" type="number" class="form-control input-sm" id="floatingInput" placeholder="123..">

            </div>
           
            <div class="form-floating mb-2">
                <label>Profile Picture:</label>
                <div class="input-group" style="width: 92%;">
                    <input type="file" id="formFile2" class="form-control" asp-for="formFile" onchange="previewImage2(this)">
                </div>
            </div>

            <button type="submit" class="btn btn-lg btn-primary btn-login text-uppercase mb-2" style="padding: 6px 18px 5px 18px;
                        margin-top: 8px;
                        font-size: 15px;
                        font-family: sans-serif;
                        font-weight: lighter;">
                Save
            </button>
            <button class="btn btn-lg btn-outline-dark text-uppercase mb-2" type="button" style="padding: 6px 18px 5px 18px;
                        margin-top: 8px;
                        font-size: 15px;
                        font-family: sans-serif;
                        font-weight: lighter;" onclick="closeModalSecondaryClient()">
                Cancel
            </button>
        </div>

        <div class="col-3" style="position: relative;">
            <img asp-formaction="" class="secondaryClientImage" id="imagePreview2" width="100%" style="margin-top: 20px; height: 160px; border: solid;" />

            @if (Model != null && Model.ImageUrl != null)
            {
                <input type="hidden" id="previousImageUrl2" src="@Model.ImageUrl" />
            }

            <button type="button" class="btn btn-custom"
                    onclick="discardImage2()">
                <i class="fas fa-trash-alt" style="color:brown;"></i>
            </button>
        </div>


    </div>
</form>
@*         </div>
    </div>
</div> *@


<script>
    var secondaryClientEmail = '@Html.Raw(SecondaryClientEmail)';

    function displayImageForSecondaryClient() {
        $.ajax({
            url: '/SecondaryClient/GetProfileImageSecondaryClient',
            type: 'GET',
            data: { email: secondaryClientEmail },
            success: function (data) {
                //debugger;
                $('.secondaryClientImage').attr('src', 'data:image/png;base64,' + data);
    @*  $('#navProfileImage').attr('src', 'data:image/png;base64,' + data); *@
                    },
            error: function (error) {
                console.error('Failed to retrieve and display image:', error);
            }
        });
    }

    function GetStateListForSecondaryClient() {
        $.ajax({
            url: '/Home/GetState', // Update the URL as needed
            type: 'GET',
            dataType: 'json',
            success: function (data) {
                console.log(data);
                try {
                    var stateDropdown = $('#stateInputSecondaryClient');
                    stateDropdown.empty(); // Clear existing options

                    // Add a default option
                    stateDropdown.append($('<option>', {
                        value: '',
                        text: '--Select State--'
                    }));

                    // Populate dropdown with state options
                    data.forEach(function (state) {
                        stateDropdown.append($('<option>', {
                            value: state.stateId,
                            text: state.stateName
                        }));
                    });
                } catch (error) {
                    console.error('Error populating state dropdown:', error);
                }
            },
            error: function (error) {
                console.log('Error fetching state data:', error);
                // Handle the error
            }
        });
    }

    function GetCountryListForSecondaryClient() {
        $.ajax({
            url: '/Home/GetCountry',
            type: 'GET',
            dataType: 'json',
            success: function (data) {
                console.log(data);
                try {
                    var countryDropdown = $('#countryInputSecondaryClient');
                    countryDropdown.empty(); // Clear existing options

                    // Add a default option
                    countryDropdown.append($('<option>', {
                        value: '',
                        text: '--Select Country--'
                    }));

                    // Populate dropdown with country options
                    data.forEach(function (country) {
                        countryDropdown.append($('<option>', {
                            value: country.countryId,
                            text: country.countryName
                        }));
                    });
                } catch (error) {
                    console.error('Error populating country dropdown:', error);
                }
            },
            error: function (error) {
                console.log('Error fetching country data:', error);
                // Handle the error
            }
        });
    }

    document.addEventListener('DOMContentLoaded', function () {
        // Retrieve the previous image URL from the hidden field
        var previousImageUrl = document.getElementById('previousImageUrl2').value;
        var imagePreview = document.getElementById('imagePreview2');

        // Check if there is a previous image URL
        if (previousImageUrl) {
            imagePreview.src = previousImageUrl;
            imagePreview.style.display = 'block';
        }
    });

    function previewImage2(input) {
        var preview = document.getElementById('imagePreview2');
        var file = input.files[0];

        if (file) {
            var reader = new FileReader();

            reader.onload = function (e) {
                preview.src = e.target.result;
                preview.style.display = 'block';
            };

            reader.readAsDataURL(file);
        } else {
            preview.src = '';
            preview.style.display = 'none';
        }
    }
    function discardImage2() {
        var fileInput = document.getElementById('formFile2');
        fileInput.value = ''; // Clear the file input
        var imagePreview = document.getElementById('imagePreview2');
        imagePreview.src = ''; // Clear the preview
        imagePreview.style.display = 'block';
    }


    function closeModalSecondaryClient() {
        // Assuming you're using jQuery for Bootstrap modal
        $('#secondaryClientEditModal').modal('hide');
    }
</script>

Sugamta.Web/Views/SecondaryClient/_SecondaryClientDetail.cshtml
@model List<SecondaryClient>

<div class="card shadow border-0 my-4">
   
    <div class="card-body p-4">
        <div class="row pb-3">
            <div class="col-6">
            </div>
        </div>

        <table id="tblData1" class="table table-bordered " style="width:100%">
            <thead>
                <tr>
                    <th>Email</th>
                    <th>Name</th>
                    <th>Creation Date</th>
                    <th>Role</th>
                    <th>
                        <div style="display: flex; justify-content: center;">
                            <button type="button" style="background: #33cfa4 !important; border: none;" onclick="renderSecondarClientAddView();" class="btn btn-primary">
                                <i class="bi bi-plus-circle"></i> Register Secondary Client 
                            </button>
                        </div>
                    </th>
                </tr>
            </thead>
        </table>

    </div>
</div>

@section Scripts {
    <script src="~/js/SecondaryClientDetail.js"></script>
}

 <script src="~/js/AddSecondaryClientView.js"></script> 