Sugamta.Web/Models/PrimaryClient.cs
namespace Sugamta.Web.Models
{
    public class PrimaryClient
    {
        public int PrimaryClientId { get; set; }

        public string PrimaryClientEmail { get; set; }
        public string PrimaryClientName { get; set; }
        public string Password { get; set; }
        public DateTime CreationDate { get; set; }
        public int RoleId { get; set; }
        public string AgencyEmail { get; set; }
        public string? OTP { get; set; }
        public DateTime OTPGeneratedDate { get; set; }
        public int IsDeleted { get; set; } = 0;
        public string AgencyName { get; set; }
    }
}

Sugamta.Web/Controllers/PrimaryClientController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Sugamta.Web.Models;
using Sugamta.Web.Models.PrimaryClientDTOs;
using Sugamta.Web.Models.UserDTOs;
using static Org.BouncyCastle.Bcpg.Attr.ImageAttrib;

namespace Sugamta.Web.Controllers
{
    public class PrimaryClientController : Controller
    {
        public async Task<ActionResult> Index()
        {
            List<PrimaryClient> userEntities = await GetPrimaryClientAsync();
            return View(userEntities);
        }


        [HttpGet]
        public async Task<ActionResult> GetPrimaryClient()
        {
            return PartialView("GetPrimaryClient");
        }

        [HttpGet]
        public async Task<IActionResult> GetAllPrimaryClient()
        {
            List<PrimaryClient> userEntities = await GetPrimaryClientAsync();
            return Json(new { data = userEntities.ToList() });
        }

        string getPrimaryClientURL = "https://localhost:7109/api/get-primary-client-all";
        public async Task<List<PrimaryClient>> GetPrimaryClientAsync()
        {
            List<PrimaryClient> userEntitiesWithRole = new List<PrimaryClient>();

            using (var client = new HttpClient())
            {
                string bearerToken = HttpContext.Session.GetString("BearerToken");

                // Set the Authorization header with the bearer token
                client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", bearerToken);

                HttpResponseMessage response = await client.GetAsync(getPrimaryClientURL);

                if (response.IsSuccessStatusCode)
                {
                    string content = await response.Content.ReadAsStringAsync();
                    List<PrimaryClient> userWithRoleDtos = JsonConvert.DeserializeObject<List<PrimaryClient>>(content);

                    userEntitiesWithRole = userWithRoleDtos.Select(dto =>
                        new PrimaryClient
                        {
                            PrimaryClientEmail = dto.PrimaryClientEmail,
                            PrimaryClientName = dto.PrimaryClientName,
                            Password = dto.Password,
                            CreationDate = dto.CreationDate,
                            IsDeleted = dto.IsDeleted,
                            AgencyName = dto.AgencyName
                        }).ToList();
                }
                else
                {
                    // Handle the error condition, you might want to log it or take other actions.
                    ModelState.AddModelError(string.Empty, "Failed to retrieve user entities. Please try again.");
                }

                return userEntitiesWithRole;
            }
        }

        [HttpGet]
        public async Task<ActionResult> Create()
        {
            return PartialView("AddPrimaryClient");
        }

        [HttpPost]
        public async Task<IActionResult> Create(PrimaryClientRegisterDto user)
        {
            if (user.PrimaryClientEmail != null)
            {

                using (var client = new HttpClient())
                {
                    HttpResponseMessage getData = await client.PostAsJsonAsync<PrimaryClientRegisterDto>("https://localhost:7109/api/add-primary-client", user);

                    if (getData.IsSuccessStatusCode)
                    {
                        TempData["PrimaryClientMessage"] = "Primary Client Registered Successfully";
                        // return RedirectToAction("Index", "Home");
                        //return View("HomePage");
                        return RedirectToAction("HomePage", "Home");

                    }
                    else
                    {
                        Console.WriteLine("Error Calling Web API");
                    }

                }
            }
            return PartialView("GetPrimaryClient");
        }

        public async Task<IActionResult> GetPrimaryClientImage(string email)
        {
            using (var client = new HttpClient())
            {
                string imageURL = $"https://localhost:7109/api/get-primary-client-image/{Uri.EscapeDataString(email)}";

                HttpResponseMessage response = await client.GetAsync(imageURL);

                if (response.IsSuccessStatusCode)
                {
                    // Assuming the API returns a base64 string directly
                    string base64Image = await response.Content.ReadAsStringAsync();

                    // Return the base64 string as content with appropriate content type
                    return Content(base64Image, "image/png"); // Adjust content type based on your image format
                }
                else
                {
                    // Return a not found result or handle the error based on your application logic
                    return NotFound();
                }
            }
        }

        [HttpGet]
        public async Task<ActionResult> Edit(string email)
        {
            ViewData["PrimaryClientEmail"] = email;
            PrimaryClientDetails userDetails = new()
            {
                PrimaryClientEmail = email
            };

            using (var client = new HttpClient())
            {

                string getClientURL = $"https://localhost:7109/api/get-primary-client-details/{Uri.EscapeDataString(userDetails.PrimaryClientEmail)}";

                HttpResponseMessage response = await client.GetAsync(getClientURL);

                if (response.IsSuccessStatusCode)
                {
                    string content = await response.Content.ReadAsStringAsync();
                    PrimaryClientDetailsEditDto fetchedUserDetails = JsonConvert.DeserializeObject<PrimaryClientDetailsEditDto>(content);
                    return PartialView("EditPrimaryClient", fetchedUserDetails);
                }
            }

            return PartialView("EditPrimaryClient");
        }

        public async Task<PrimaryClientDetails> GetPrimaryClientDetailsForCreationOrUpdate(string email)
        {
            using (var client = new HttpClient())
            {
                string apiUrl = $"https://localhost:7109/api/get-primary-client-details-for-create-or-update/{Uri.EscapeDataString(email)}";

                HttpResponseMessage response = await client.GetAsync(apiUrl);

                if (response.IsSuccessStatusCode)
                {
                    // Assuming the API returns JSON
                    // UserDetails userDetails = await response.Content.ReadAsAsync<UserDetails>();
                    // return userDetails;
                    string content = await response.Content.ReadAsStringAsync();

                    // Deserialize the string into UserDetailsDto using JSON serializer
                    PrimaryClientDetails userDetails = JsonConvert.DeserializeObject<PrimaryClientDetails>(content);

                    return userDetails;
                }
                else
                {
                    return null;
                }
            }
        }

        string UpdatePrimaryClientDetailsURL = "https://localhost:7109/api/update-primary-client-details";
        string AddPrimaryClientDetailsURL = "https://localhost:7109/api/add-primary-client-details";
        [HttpPost]
        public async Task<IActionResult> AddOrUpdatePrimaryClientDetails(PrimaryClientDetailsCreateOrUpdateDto userDetails)
        {
            try
            {
               // userDetails.PrimaryClientEmail = HttpContext.Session.GetString("UserEmail");

                var existingUser = await GetPrimaryClientDetailsForCreationOrUpdate(userDetails.PrimaryClientEmail);

                var formData = new MultipartFormDataContent();

                formData.Add(new StringContent(userDetails.PrimaryClientEmail), "PrimaryClientEmail");
                formData.Add(new StringContent(userDetails.Address), "Address");
                formData.Add(new StringContent(userDetails.City), "City");
                /* formData.Add(new StringContent(userDetails.StateId), "State");
                 formData.Add(new StringContent(userDetails.CountryId), "Country");*/

                formData.Add(new StringContent(userDetails.StateId.ToString()), "StateId");
                formData.Add(new StringContent(userDetails.CountryId.ToString()), "CountryId");
                formData.Add(new StringContent(userDetails.PhoneNumber), "PhoneNumber");
                formData.Add(new StringContent(userDetails.AlternatePhoneNumber), "AlternatePhoneNumber");

                // Check if formFile is not null and has content
                if (userDetails.formFile != null && userDetails.formFile.Length > 0)
                {
                    // Add the file content
                    formData.Add(new StreamContent(userDetails.formFile.OpenReadStream())
                    {
                        Headers =
                                    {
                                        ContentLength = userDetails.formFile.Length,
                                        ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue(userDetails.formFile.ContentType)
                                    }
                    },
                    "formFile", userDetails.formFile.FileName);
                }

                if (existingUser != null)
                {
                    // User already exists, call the update API
                    using (var client = new HttpClient())
                    {
                        client.BaseAddress = new Uri(UpdatePrimaryClientDetailsURL);

                        // Send the PUT request with multipart/form-data
                        HttpResponseMessage response = await client.PutAsync("https://localhost:7109/api/update-primary-client-details", formData);

                        if (response.IsSuccessStatusCode)
                        {

Sugamta.Web/Views/PrimaryClient/AddPrimaryClient.cshtml
@model Sugamta.Web.Models.PrimaryClientDTOs.PrimaryClientRegisterDto

@* <div id="profilePopup" class="modal fade profileform">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content pl-4 pr-4"> *@
<!-- Popup content goes here -->
<form asp-controller="PrimaryClient" asp-action="Create" method="post" enctype="multipart/form-data">
    <div class="modal-header">
        <h5 class="modal-title">Primary Client</h5>
        <button type="button" class="close" style="color: red;" data-dismiss="modal" onclick="closeAddModalPrimaryClient()">&times;</button>
    </div>
    <div class="row">
        <div class="modal-body col-9">
            <!-- Your profile content goes here -->
            <div class="form-floating mb-2">
                <label  for="floatingInput">Email</label>
                <input id="emailInput" asp-for="PrimaryClientEmail"  type="email" class="form-control input-sm" id="floatingInput" placeholder="examp@gmail.com" required>
            </div>

            <div class="form-floating mb-2">
                <label for="floatingInput">Name</label>
                <input id="nameInput" asp-for="PrimaryClientName" type="text" class="form-control input-sm" id="floatingInput" placeholder="name" required>
            </div>

            <div class="form-floating mb-2">
                <label for="floatingInput">Password</label>
                <input id="addressInput" asp-for="Password" type="text" class="form-control input-sm" id="floatingInput" placeholder="name" required>
            </div>

            <div class="form-floating mb-2">
                <label for="floatingInput">AgencyEmail</label>
                <input id="agencyEmailInput" asp-for="AgencyEmail" type="email" class="form-control input-sm" id="floatingInput" placeholder="examp@gmail.com" required>
            </div>


            <div class="form-floating mb-3">
                <label for="floatingInput">Role Type</label>
                <select asp-for="RoleId" type="text" class="form-control form-select form-select-sm " id="floatingInput" aria-label="small select example" style="width: 359px; margin-left: 151px;">
                    <option selected value="6">Primary Client</option>
                </select>               
            </div>
            <div class="form-check mb-3">
                <input class="form-check-input" type="checkbox" value="" id="rememberPasswordCheck">
                <label class="form-check-label" for="rememberPasswordCheck">
                    Remember password
                </label>
            </div>

            <button type="submit" class="btn btn-lg btn-primary btn-login text-uppercase mb-2" style="padding: 6px 18px 5px 18px;
                        margin-top: 8px;
                        font-size: 15px;
                        font-family: sans-serif;
                        font-weight: lighter;">
                Save
            </button>
            <button class="btn btn-lg btn-outline-dark text-uppercase mb-2" type="button" style="padding: 6px 18px 5px 18px;
                        margin-top: 8px;
                        font-size: 15px;
                        font-family: sans-serif;
                        font-weight: lighter;" onclick="closeAddModalPrimaryClient()">
                Cancel
            </button>
        </div>



    </div>
</form>
@*         </div>
    </div>
</div> *@

<script>

    function closeAddModalPrimaryClient() {
        // Assuming you're using jQuery for Bootstrap modal
        $('#primaryClientAddModal').modal('hide');
    }



</script>

Sugamta.Web/Views/PrimaryClient/DeletePrimaryClient.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Sugamta.Web/Views/PrimaryClient/EditPrimaryClient.cshtml
@model Sugamta.Web.Models.PrimaryClientDTOs.PrimaryClientDetailsEditDto
@{
    var PrimaryClientEmail = ViewData["PrimaryClientEmail"];
}

@* <div id="profilePopup" class="modal fade profileform">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content pl-4 pr-4"> *@
<!-- Popup content goes here -->
<form asp-controller="PrimaryClient" asp-action="AddOrUpdatePrimaryClientDetails" method="post" enctype="multipart/form-data">
    <div class="modal-header">
        <h5 class="modal-title">Primary Client Details</h5>
        <button type="button" class="close" style="color: red;" data-dismiss="modal" onclick="closeModalPrimaryClient()">&times;</button>
    </div>
    <div class="row">
        <div class="modal-body col-9">
            <!-- Your profile content goes here -->
            @* <div class="form-floating mb-2">
                <label for="floatingInput">Email</label>
                <input id="emailInput" asp-for="PrimaryClientEmail" disabled type="email" class="form-control input-sm" id="floatingInput" placeholder="examp@gmail.com" >

            </div> *@

            <div class="form-floating mb-2">
                <label for="floatingInput">Email</label>

                @if (Model == null)
                {
                    <!-- Display the email value, but disable the input -->
                    <input id="emailInput" asp-for="PrimaryClientEmail" disabled value="@PrimaryClientEmail" type="email" class="form-control input-sm" id="floatingInput" mailto:placeholder="examp@gmail.com">

                    <!-- Hidden input to store the email value for submission -->
                    <input type="hidden" asp-for="PrimaryClientEmail" value="@PrimaryClientEmail" />
                }
                else
                {
                    <!-- Display the email value as a disabled input -->
                    <input id="emailInput" asp-for="PrimaryClientEmail" disabled type="email" class="form-control input-sm" id="floatingInput" mailto:placeholder="examp@gmail.com">

                    <!-- Hidden input to store the email value for submission -->
                    <input type="hidden" asp-for="PrimaryClientEmail" />
                }
            </div>
             

            @* <div class="form-floating mb-2">
                <label for="floatingInput">Email</label>
                <!-- Display the email value, but disable the input -->
                <input id="emailInput" asp-for="PrimaryClientEmail" disabled type="email" class="form-control input-sm" id="floatingInput" placeholder="examp@gmail.com">

                <!-- Hidden input to store the email value for submission -->
                <input type="hidden" asp-for="PrimaryClientEmail" />
            </div> *@


            <div class="form-floating mb-2">
                <label for="floatingInput">Address</label>
                <input id="addressInput" asp-for="Address" type="text" class="form-control input-sm" id="floatingInput" placeholder="name">
            </div>
            <div class="form-floating mb-2">
                <label for="floatingInput">City</label>
                <input id="cityInput" asp-for="City" type="text" class="form-control input-sm" id="floatingInput" placeholder="name">
            </div>

            <div class="form-floating mb-3">
                <label for="stateInputPrimaryClient">State</label>
                <div style="display: flex;">
                    <input id="" style="width: 32%;" asp-for="State" type="text" class="form-control input-sm" id="floatingInput" placeholder="state">
                    <select id="stateInputPrimaryClient" asp-for="StateId" class="form-control form-select form-select-sm" aria-label="small select example" style="width: 33%;">
                        @* <option selected></option> *@
                        @foreach (var state in ViewBag.StateList as List<State> ?? new List<State>())
                        {
                            <option value="@state.StateId">@state.StateName</option>
                        }
                    </select>
                </div>
           
            </div>
            <div class="form-floating mb-3">
                <label for="countryInputPrimaryClient">Country</label>
                <div style="display: flex;">
                    <input id="" style="width: 32%;" asp-for="Country" type="text" class="form-control input-sm" id="floatingInput" placeholder="country">
                    <select id="countryInputPrimaryClient" asp-for="CountryId" class="form-control form-select form-select-sm" aria-label="small select example" style="width: 33%; z-index: 1000;">
                        @* <option>--Select Country--</option> *@
                        @foreach (var country in ViewBag.CountryList as List<Country> ?? new List<Country>())
                        {
                            <option selected value="@country.CountryId">@country.CountryName</option>
                        }
                    </select>
                </div>              
            </div>

            <div class="form-floating mb-2">
                <label for="floatingInput">Phone Number</label>
                <input id="phoneInput" asp-for="PhoneNumber" type="number" class="form-control input-sm" id="floatingInput" placeholder="12345">

            </div>
            <div class="form-floating mb-2">
                <label for="floatingInput">Alternate PhoneNo</label>
                <input id="alternatePhoneInput" asp-for="AlternatePhoneNumber" type="number" class="form-control input-sm" id="floatingInput" placeholder="123..">

            </div>

            <div class="form-floating mb-2">
                <label>Profile Picture:</label>
                <div class="input-group" style="width: 92%;">
                    <input type="file" id="formFile1" class="form-control" asp-for="formFile" onchange="previewImage1(this)">
                </div>
            </div>

            <button type="submit" class="btn btn-lg btn-primary btn-login text-uppercase mb-2" style="padding: 6px 18px 5px 18px;
                        margin-top: 8px;
                        font-size: 15px;
                        font-family: sans-serif;
                        font-weight: lighter;">
                Save
            </button>
            <button class="btn btn-lg btn-outline-dark text-uppercase mb-2" type="button" style="padding: 6px 18px 5px 18px;
                        margin-top: 8px;
                        font-size: 15px;
                        font-family: sans-serif;
                        font-weight: lighter;" onclick="closeModalPrimaryClient()">
                Cancel
            </button>
        </div>

        <div class="col-3" style="position: relative;">
            <img asp-formaction="" class="primaryClientImage" id="imagePreview1" width="100%" style="margin-top: 20px; height: 160px; border: solid;" />

            @if (Model != null && Model.ImageUrl != null)
            {
                <input type="hidden" id="previousImageUrl1" src="@Model.ImageUrl" />
            }

            <button type="button" class="btn btn-custom"
                    onclick="discardImage1()">
                <i class="fas fa-trash-alt" style="color:brown;"></i>
            </button>
        </div>


    </div>
</form>
@*         </div>
    </div>
</div> *@


<script src="~/js/PrimaryClientDetails.js"></script>
<script>
    var primaryClientEmail = '@Html.Raw(PrimaryClientEmail)';

    function displayImageForPrimaryClient() {
        $.ajax({
            url: '/PrimaryClient/GetPrimaryClientImage',
            type: 'GET',
            data: { email: primaryClientEmail },
            success: function (data) {
                //debugger;
                $('.primaryClientImage').attr('src', 'data:image/png;base64,' + data);
                updateNavProfileImage(data);
    @*  $('#navProfileImage').attr('src', 'data:image/png;base64,' + data); *@
                    },
            error: function (error) {
                console.error('Failed to retrieve and display image:', error);
            }
        });
    }

    document.addEventListener('DOMContentLoaded', function () {
    // Retrieve the previous image URL from the hidden field
    var previousImageUrl = document.getElementById('previousImageUrl1').value;
    var imagePreview = document.getElementById('imagePreview1');

    // Check if there is a previous image URL
    if (previousImageUrl) {
        imagePreview.src = previousImageUrl;
        imagePreview.style.display = 'block';
    }
    });

    function previewImage1(input) {
    var preview = document.getElementById('imagePreview1');
    var file = input.files[0];

    if (file) {
        var reader = new FileReader();

        reader.onload = function (e) {
            preview.src = e.target.result;
            preview.style.display = 'block';
        };

        reader.readAsDataURL(file);
    } else {
        preview.src = '';
        preview.style.display = 'none';
    }
}
    function discardImage1() {
        var fileInput = document.getElementById('formFile1');
        fileInput.value = ''; // Clear the file input
        var imagePreview = document.getElementById('imagePreview1');
        imagePreview.src = ''; // Clear the preview
        imagePreview.style.display = 'block';
    }

    function closeModalPrimaryClient() {
        // Assuming you're using jQuery for Bootstrap modal
        $('#primaryClientEditModal').modal('hide');
    }

    function GetCountryListForPrimaryClient() {
        $.ajax({
            url: '/Home/GetCountry',
            type: 'GET',
            dataType: 'json',
            success: function (data) {
                console.log(data);
                try {
                    var countryDropdown = $('#countryInputPrimaryClient');
                    countryDropdown.empty(); // Clear existing options

                    // Add a default option
                    countryDropdown.append($('<option>', {
                        value: '',
                        text: '--Change Country--'
                    }));

                    // Populate dropdown with country options
                    data.forEach(function (country) {
                        countryDropdown.append($('<option>', {
                            value: country.countryId,
                            text: country.countryName
                        }));
                    });
                } catch (error) {
                    console.error('Error populating country dropdown:', error);
                }
            },
            error: function (error) {
                console.log('Error fetching country data:', error);
                // Handle the error
            }
        });
    }

    function GetStateListForPrimaryClient() {
        $.ajax({
            url: '/Home/GetState', // Update the URL as needed
            type: 'GET',
            dataType: 'json',
            success: function (data) {
                console.log(data);
                try {
                    var stateDropdown = $('#stateInputPrimaryClient');
                    stateDropdown.empty(); // Clear existing options

                    // Add a default option
                    stateDropdown.append($('<option>', {
                        value: '',
                        text: '--Change State--'
                    }));

                    // Populate dropdown with state options
                    data.forEach(function (state) {
                        stateDropdown.append($('<option>', {
                            value: state.stateId,
                            text: state.stateName
                        }));
                    });
                } catch (error) {
                    console.error('Error populating state dropdown:', error);
                }
            },
            error: function (error) {
                console.log('Error fetching state data:', error);
                // Handle the error
            }
        });
    }

    function displayImageForPrimaryClient() {
        $.ajax({
            url: '/PrimaryClient/GetPrimaryClientImage',
            type: 'GET',
            data: { email: primaryClientEmail },
            success: function (data) {
                //debugger;
                $('.primaryClientImage').attr('src', 'data:image/png;base64,' + data);
                updateNavProfileImage(data);
    @*  $('#navProfileImage').attr('src', 'data:image/png;base64,' + data); *@
                },
            error: function (error) {
                console.error('Failed to retrieve and display image:', error);
            }
        });
    }

</script>

Sugamta.Web/Views/PrimaryClient/GetPrimaryClient.cshtml
@model List<PrimaryClient>

<div class="card shadow border-0 my-4">
    @* <div class="card-header bg-secondary bg-gradient ml-0 py-3">
    <div class="row">
    <div class="col-12 text-center">
    <h2 class="text-white py-2">User List</h2>
    </div>
    </div>
    </div> *@
    <div class="card-body p-4">
        <div class="row pb-3">
            <div class="col-6">
            </div>
            @*             <div class="col-6 text-end">
            <a asp-controller="Product" asp-action="Upsert" class="btn btn-primary">
            <i class="bi bi-plus-circle"></i> Add New User
            </a>
            </div> *@
        </div>

        <table id="primaryClientTable" class="table table-bordered " style="width:100%">
            <thead>
                <tr>
                    <th>Email</th>
                    <th>Name</th>
                    <th>Creation Date</th>
                    <th>AgencyName</th>
                    <th>
                        <div style="display: flex; justify-content: center;">
                            <button type="button" style="background: #33cfa4 !important; border: none;" onclick="RenderPrimaryClientAddView();" class="btn btn-primary">
                                <i class="bi bi-plus-circle"></i> Add New PrimaryClient
                            </button>
                        </div>
                    </th>
                </tr>
            </thead>
        </table>

    </div>
</div>

@section Scripts {
    <script src="~/js/PrimaryClientDetails.js"></script>
}

<script src="~/js/AddPrimaryClientView.js"></script>